### ISSUE TITLE
output_classes.pkl webaddress for assets download is unreachable

### ISSUE THREAD

**Issue by LegallyOverworked** [datax-lab/ECPICK#5]
Can you check/update the assets download location? It seems like the models necessary for the tool are not available, as during setup it fails. Solving the problem manually is not possible because the .pkl file address are not available.

wget https://download.sharenshare.kr/ecpick/output_classes.pkl

**See**

$ wget https://download.sharenshare.kr/ecpick/output_classes.pkl
--2024-03-19 11:42:23--  https://download.sharenshare.kr/ecpick/output_classes.pkl
Resolving download.sharenshare.kr (download.sharenshare.kr)... 175.115.168.53
Connecting to download.sharenshare.kr (download.sharenshare.kr)|175.115.168.53|:443...
failed: Connection timed out.
Retrying.

**See complete error below:**

2024-03-19 11:30:29   INFO : #### CUDA Settings ####
2024-03-19 11:30:29   INFO : > Is CUDA available? False
2024-03-19 11:30:29   INFO : #### Load Predictable Classes ####
2024-03-19 11:30:29   INFO : > Load output classes
2024-03-19 11:30:29   WARN : > Not Exist Classes file. Start download

Traceback (most recent call last):
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x14bde01ab130>: Failed to establish a new connection: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='download.sharenshare.kr', port=443): Max retries exceeded with url: /ecpick/output_classes.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14bde01ab130>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/ecpick/run_ecpick.py", line 11, in <module>
    ecpick = ECPICK()
  File "/lustre1/project/stg_00142/sandbox/enzyme-classification-dev/src/tools/ecpick/ecpick/ecpick.py", line 74, in __init__
    download_file(url, output_path=class_path)
  File "/lustre1/project/stg_00142/sandbox/enzyme-classification-dev/src/tools/ecpick/ecpick/util/downloader.py", line 6, in download_file
    response = requests.get(url, stream=True)
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/leuven/331/vsc33189/miniconda3/envs/enzclass_ecpick/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='download.sharenshare.kr', port=443): Max retries exceeded with url: /ecpick/output_classes.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14bde01ab130>: Failed to establish a new connection: [Errno 110] Connection timed out'))

ERROR conda.cli.main_run:execute(124): `conda run python ./tools/ecpick/run_ecpick.py example.fasta ../out/out_epick` failed. (See above for error)

**Comment by duveen** [comment]
For security reasons, you cannot download it in countries other than certain countries.
Countries allowed: Korea, Japan, the United States, Australia

I will arrange to download the update file from GitHub soon.

Thank you.
